defaults:
  - _self_
  - dirs: my_dir

common:
  device: "cuda"
  num_workers: 4
  batch_size: 128
  train_epochs: 100
  test_epochs: 20
  seed: 16

split: 'train'

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}